### ISSUE TITLE
mower control

### ISSUE THREAD

**Issue by ciechompl** [stefanlaheij/hassio-addons#14]
in order to make mower control working again seems we need some change in the code ... please see this https://github.com/virtualzone/landroid-bridge/issues/88#issuecomment-605644864

**Comment by hirschy81** [comment]
Yes, there seems to be a new docker with working connection - could you please update this addon to the newest version? Thx

**Comment by stefanlaheij** [comment]
I updated the package reference. If you rebuild the add-on it uses the new code.
