### ISSUE TITLE
Can't build ceecc69e/amd64-addon-landroids:0.72

### ISSUE THREAD

**Issue by MuppetOwl** [stefanlaheij/hassio-addons#15]
I get this error now: 
Can't build ceecc69e/amd64-addon-landroids:0.72: The command '/bin/ash -o pipefail -c npm run grunt' returned a non-zero code: 3

I had this one working before but was trying to rebuild when it failed. Tried to uninstall and install again with same error.

Using Home Assistant 0.109.2

**Comment by olskar** [comment]
Same issue here

20-06-14 08:49:10 INFO (SyncWorker_0) [supervisor.docker.addon] Start build ceecc69e/amd64-addon-landroids:0.72
20-06-14 08:49:13 ERROR (SyncWorker_0) [supervisor.docker.addon] Can't build ceecc69e/amd64-addon-landroids:0.72: The command '/bin/ash -o pipefail -c apk --no-cache --virtual build-dependencies add     python     make     g++     && npm install' returned a non-zero code: 2

**Comment by guillpocovi** [comment]
same here. Anybody managed to fix it?

**Comment by guillpocovi** [comment]
The fix is to replace "python" with "python2" in the Dockerfile. More info here: https://github.com/docker-library/docker/issues/240

**Comment by MuppetOwl** [comment]
Im instead using this component.
https://github.com/mtrab/landroid_cloud/

Its working and also possible to install using HACS. Look like this one is no longer updated.
