### ISSUE TITLE
Update for OpenSprinkler Add-On?

### ISSUE THREAD

**Issue by jonathanware** [stefanlaheij/hassio-addons#16]
Hi there,

I just switched over from HomeBridge to Home Assistant and I’m looking to install OpenSprinkler on the same Pi. I attempted to install your add-on but it threw an error (COPY failed: stat OpenSprinkler-Firmware/OpenSprinkler: file does not exist.)

Are there any plans to update the add-on? Or do you know of a better solution?

Thank you!

**Comment by stefanlaheij** [comment]
Hi @jonathanware,
Great choice to switch to Home Assistant! My add-on is not working anymore. 
You can find a better solution here: https://github.com/vinteo/hass-opensprinkler
This is an actively maintained add-on that you can install via HACS (Home Assistant Community Store).
Stefan

**Comment by jonathanware** [comment]
That add on assumes you already have opensprinkler installed on another device, correct? I think I might need to switch from HAOS to core since I'm trying to install it on the same device.

**Comment by stefanlaheij** [comment]
Ah yes, that is correct. I forgot about the fact that I moved my Home Assistant to a separate device. 
I am sorry, but I am not maintaining this add-on anymore.
