### ISSUE TITLE
COPY failed: stat OpenSprinkler-Firmware/OpenSprinkler: file does not exist

### ISSUE THREAD

**Issue by derbrowser** [stefanlaheij/hassio-addons#17]
Hi, I am very interested in trying out your OpenSprinkler Firmware Add-on for Homeassistant. However, when trying to Install the Add-On it fails with the following error: "COPY failed: stat OpenSprinkler-Firmware/OpenSprinkler: file does not exist".

**Comment by stefanlaheij** [comment]
Hi @derbrowser , 

This add-on is not supported anymore for a long time.
Please take a look at https://github.com/vinteo/hass-opensprinkler

Br
