### ISSUE TITLE
Error on update re stack guard

### ISSUE THREAD

**Issue by charlietomo** [stefanlaheij/hassio-addons#2]
I recently rebuilt my Unifi add-on which updated from 5.6.26 > 5.7.23.

In the log I now get the following error which I am unsure how to fix? Any assistance appreciated.

`Java HotSpot(TM) Client VM warning: You have loaded library /usr/lib/unifi/lib/native/Linux/armv7/libubnt_webrtc_jni.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.`

**Comment by stefanlaheij** [comment]
Hi @charlietomo,

As you might know there is now an official maintained add-on for this: https://community.home-assistant.io/t/community-hass-io-add-on-unifi-controller/56297

**Comment by charlietomo** [comment]
Whoa, nope I didn't know that - thank @stefanlaheij.
