### ISSUE TITLE
OpenSprinkler Firmware Update

### ISSUE THREAD

**Issue by jjanderson** [stefanlaheij/hassio-addons#3]
Hi, 

I have a notice that the firmware needs to be updated, however the instructions assume I have full control over ssh which I don't.

Additionally, in my log, I see the follwoing:

sh: ./updater.sh: not found

Can you help getting the platform updated?

Thanks

**Comment by stefanlaheij** [comment]
Hi @jjanderson ,

I updated the add-on to use the latest firmware (2.1.8)
Can you try to update the add-on and let me know if this worked for you?

**Comment by jjanderson** [comment]
Hi, 

Updating from hassio UI addons does not work. I am running hass v 0.77.3

i uninstalled opensprinkler and then tried to re-install, but now the same as the upgrade, simply did not work.

```
18-10-13 08:01:30 INFO (SyncWorker_17) [hassio.docker.addon] Start build ceecc69e/armhf-addon-opensprinkler:0.4
18-10-13 08:01:37 ERROR (SyncWorker_17) [hassio.docker.addon] Can't build ceecc69e/armhf-addon-opensprinkler:0.4: The command '/bin/sh -c wget https://github.com/OpenSprinkler/OpenSprinkler-Firmware/archive/218.zip &&     unzip master.zip &&     cd /OpenSprinkler-Firmware-master &&     ./build.sh -s ospi' returned a non-zero code: 9
18-10-13 08:05:30 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
```

also when the component is loaded, and you go to the component tile, when you click on the "opensprinkler page" - The info one not the web ui, this link does not take you to the more info on the component page.

Let me know if you need me to try anything else?

Thanks for your help

**Comment by jjanderson** [comment]
Run the OpenSprinkler Pi (OSPi) firmware on top of Hass.io.
Visit OpenSprinkler page for details. --> This page is broken It goes to /hassio/addon/null

**Comment by jjanderson** [comment]
Also, when I click on the "open web ui" link, it goes to port 81, which should be port 8080...

**Comment by MatthewV19** [comment]
I'm having all the same problems listed above, happy to help out with any troubleshooting. Unfortunately, I kind of need opensprinkler working before my lawns die, and I'm not too sure where to go with trying to get this working with hass.io and docker.

Specifically, I can't get 0.4 to install, and I was struggling to get 0.3 updated before I uninstalled it.

**Comment by stefanlaheij** [comment]
> I'm having all the same problems listed above, happy to help out with any troubleshooting. Unfortunately, I kind of need opensprinkler working before my lawns die, and I'm not too sure where to go with trying to get this working with hass.io and docker.
> 
> Specifically, I can't get 0.4 to install, and I was struggling to get 0.3 updated before I uninstalled it.

Hi @MatthewV19 ,

Do you run ResinOS or HassOS on your RPi?

Regards, Stefan

**Comment by MatthewV19** [comment]
Hi Stefan,

This is a ResinOS based hass.io setup. Installed from the home assistant provided image around Home Assistant 0.70, progressively upgraded to 0.80.1. I can't get it to upgrade to 0.81 at the moment.

P.S. - Thanks for your work putting these add-ons together, I use both the OpenSprinkler add-on and the Unifi controller.

Regards,
Matt

**Comment by stefanlaheij** [comment]
Hi @MatthewV19 ,

I have updated the add-on. Could you give it another try?

Stefan

**Comment by jjanderson** [comment]
I will give it another try, but I had an issue with the Pi this was running on, so I have it as a standalone, dedicated opensprinkler now...

**Comment by MatthewV19** [comment]
Perfect, thank you! All installs and runs OK, as best I can tell. Just need to find my backup file somewhere and restore that.
