### ISSUE TITLE
OpenSprinkler Hassos 32bit

### ISSUE THREAD

**Issue by jjanderson** [stefanlaheij/hassio-addons#5]
Hi,

I believe now that the 32bit version of Hassos supports gpio.

Can you confirm if the opensprinkler addon is now supported on this OS?

Thanks

**Comment by stefanlaheij** [comment]
Hi @jjanderson,

Unfornately I cannot because I have a different setup now.
Can you test it?

Stefan

**Comment by jjanderson** [comment]
will try, will be really good to get this working on same sytem that I need to get the data from the BLE MiFlora sensors... but both BLE and GPIO seem to be the victim of Hassos tribulations and so now I am having to run 2 raspberry pi's just to monitor and water the plants!

Will give it a go tonight and report back...

Thanks
