### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by hschroyen** [stefanlaheij/hassio-addons#8]
Hello,

Seems that several people are unable to install this.
All of us get the following error message in home assistant version 0.97.2 Hassio system 184

> 19-08-28 02:14:50 INFO (SyncWorker_8) [hassio.docker.addon] Start build ceecc69e/amd64-addon-landroids:0.71

> 19-08-28 02:14:57 ERROR (SyncWorker_8) [hassio.docker.addon] Can't build ceecc69e/amd64-addon-landroids:0.71: The command '/bin/ash -o pipefail -c npm run build-prod' returned a non-zero code: 3 

Also check https://community.home-assistant.io/t/control-worx-landroid-s-via-hassio/57456/68

Thanks for looking into this

**Comment by ronmichel** [comment]
@stefanlaheij Why do we need this in the Dockerfile and how can we change it that it doesn't throw an error?

> RUN npm run build-prod

**Comment by stefanlaheij** [comment]
> @stefanlaheij Why do we need this in the Dockerfile and how can we change it that it doesn't throw an error?
> 
> > RUN npm run build-prod

Hi @ronmichel, 
this is for building the application. You also see this line in the Dockerfiles from the repo that is pulled.

**Comment by larronni** [comment]
Same error on 98.4

```
19-09-09 19:23:44 INFO (SyncWorker_19) [hassio.docker.addon] Start build ceecc69e/armv7-addon-landroids:0.71
19-09-09 19:24:09 ERROR (SyncWorker_19) [hassio.docker.addon] Can't build ceecc69e/armv7-addon-landroids:0.71: The command '/bin/ash -o pipefail -c npm run build-prod' returned a non-zero code: 3
```

Any solution on this error @stefanlaheij ?

**Comment by Juice2019** [comment]
Same error on 98.5 
`[hassio.docker.addon] Can't build ceecc69e/amd64-addon-landroids:0.71: The command '/bin/ash -o pipefail -c npm run build-prod' returned a non-zero code: 3`
Hope on a solution!

**Comment by ronmichel** [comment]
@stefanlaheij 

I did the following with the dockerfile and now it works:

````
ARG BUILD_FROM
FROM $BUILD_FROM

RUN apk add --no-cache jq wget git nodejs nodejs-npm
RUN mkdir -p /usr/src/landroid-bridge
WORKDIR /usr/src/landroid-bridge

RUN cd /usr/src && \
    git clone https://github.com/virtualzone/landroid-bridge.git && \
    cd /usr/src/landroid-bridge

RUN apk --no-cache --virtual build-dependencies add \
    python \
    make \
    g++ \
    && npm install

RUN npm run clean
RUN npm run grunt
RUN npm prune --production
RUN apk del build-dependencies
COPY run.sh /
RUN chmod a+x /run.sh

COPY config_template.json /usr/src/landroid-bridge/config.json

VOLUME /data

EXPOSE 3000

CMD [ "/run.sh" ]
````

(just run the three commands for `npm run build-prod` separately and move `apk del build-dependencies` to a later stage)

**Comment by stefanlaheij** [comment]
Thanks @ronmichel 
I will update the Dockerfile with these changes!

**Comment by hschroyen** [comment]
Thanks for the update but it seems still not to install.
When I install this it hangs my systems as it consumes all the memory.

Also other users report the same problem.

Please reopen and check

Thanks

**Comment by ronmichel** [comment]
My System is a Rasberry 3B+ with 32bit hassos. Which System are you using? Build takes ~10minutes and runs without problems.

**Comment by hschroyen** [comment]
Hello

I have hassio running on ubuntu linux on a vm.
See also the comments in https://community.home-assistant.io/t/control-worx-landroid-s-via-hassio/57456/78

Regards
